import pdfmaker

text="""[text]Hello world[/text]
generated by aditya patil

FIR (First Information Report)
 
UNDER SECTION 153(1) CR.PC, 
IN THE MATTER OF UNIVERSAL TRADING SOLUTIONS SHARE FRAUD CASE.

[1.0] INFORMATION

FORM IF1- Integrated FIR.

(i) Indian Penal Code, 1860 (IPC)
Sections 406, 420 (Cheating and dishonestly inducing delivery of property), 504 (Intentional insult with intent to provoke breach of the peace).

(ii) Companies Act, 2013
Section 42 (Fraudulent conveyance or preference).

[2.0] OCCURRENCE OF OFFENCE

(a) Day: 14th & 17th February, 2109.
(b) Information received at Police Station: 16th September, 2320.
(c) General Diary (GD) Reference: N/A

[3.0] TYPE OF INFORMATION AND LOCATION

Type: Written

[4.0] LOCATION OF OFFENCE AND DETAILS OF PARTIES

(5.1) Place of Occurrence
Address: Universal Trading Solutions, [Location], [City], Tamil Nadu, India.
[5.2] Complainant/Informant
Name: Vinayan
Father's Name: Chandrasekara Nair
Date of Birth: [D.O.B.]
Nationality: Indian
Passport No.: [Passport No.]
Issue Date: [Issue Date]
Place of Issue: [Place of Issue]
Address: [Address]

[6.0] KNOWN/SUSPECTED/UNKNOWN ACCUSED

(7.1) Accused 1:
Name: Gautham Ramesh
Address: Chinnathotham Ponnankanni
City: Coimbatore
Tamil Nadu
India

Accused 1's Father's/Husband's Name, Date of Birth, Nationality, Passport No., Issue Date, Place of Issue, and Occupation are not mentioned in the provided information.

Details of other accused (Accused 2, 3, and 4):
Name: S. Shah Janah, Manthan Gopalan, Arjuna
Addresses: [Addresses]
[City, State, Country]: [City], [State], India

[7.2] REASONS FOR DELAY IN REPORTING BY THE COMPLAINANT/INFORMANT

[8.0] PARTICULARS OF PROPERTIES STOLEN/INVOLVED

Total value of the deposited amount: INR 6 Lakhs

[9.0] ADDITIONAL REMARKS

An inquest report or U.D. case number, if any, is not mentioned.

The FIR has been registered under Cr. No. RC0323020A088 at the Perintalmanna Police Station.

Action taken: The case has been registered, and the investigation is being carried out by the concerned authorities. The complainant has been informed about the registration of the FIR and has been given a free copy of the same.

Officer-in-Charge: [Name], [Rank], [Police Station]

Signature: [Signature]

Date & Time of Despatch to the Court: [Date & Time]"""


pdfmaker.create_pdf(text)